services:
  db:
    image: postgres:latest
    container_name: microwave-benner-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: microwave-benner
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: ./Dockerfile.migrate
    container_name: microwave-benner-migrate
    depends_on:
      db:
        condition: service_started
    environment:
      - DB_CONNECTION=Host=db;Port=5432;Username=postgres;Password=1234;Database=microwave-benner;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Timeout=15;

  api:
    build:
      context: .
      dockerfile: microwave-benner.Server/Dockerfile
    container_name: microwave-benner-api
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "5000:80"
    environment:
      - DB_CONNECTION=Host=db;Port=5432;Username=postgres;Password=1234;Database=microwave-benner;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Timeout=15;
      - ALLOWED_ORIGINS=http://localhost:5173,http://microwave-benner-client:80

  client:
    build:
      context: .
      dockerfile: microwave-benner.client/Dockerfile
    container_name: microwave-benner-client
    ports:
      - "5173:80"
    depends_on:
      api:
        condition: service_started

volumes:
  db-data:
